# Generated by Django 4.1.5 on 2023-01-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_urlyvisit_visited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urly',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
